SELECT
SITE_HOLDER.NODO as NODO,
SUBSTRING(T.CODIGO, 3, 4) AS DIVICAU,
D.CODIGO AS DIVISOR,
T.CODIGO AS CTO,
BR.CODIGO AS POSICION_CTO_BORNE,
EO.NOMBRE AS ESTADO_BORNE,
BR.LINE_ID,
BR.VNO_CODE
FROM [Red].[Terminal] AS T
    JOIN [Red].[DIVISOR] D ON D.ID_TERMINAL = T.ID_TERMINAL
    JOIN [Red].[BORNE] BR ON BR.ID_DIVISOR = D.ID_DIVISOR
	JOIN red.DOM_ESTADO_OCUPACION EO ON EO.ID_ESTADO_OCUPACION = BR.ID_ESTADO_OCUPACION
    JOIN [Infraestructura].[SITE_HOLDER] ON SITE_HOLDER.NODO = SUBSTRING(T.CODIGO, 1, 2)
WHERE (T.ID_CLASIFICACION_TERMINAL = 1001 OR T.ID_CLASIFICACION_TERMINAL = 1002)
        AND SITE_HOLDER.ID_TIPO_SITE = 1002
		/*AND SUBSTRING(T.CODIGO, 1, 2) = 'ZA'
		AND BR.LINE_ID IS NOT NULL*/