-- CABLE MENSAJERO - PUNTO DE ACCESO

SELECT * FROM Infraestructura.CABLE_MENSAJERO MEN
WHERE MEN.ID_CABLE_MENSAJERO = 711544  -- SE DEBE CREAR UNA COLUMNA ID_PA A TABLA DE CABLE MENSAJERO PARA AMARRARLO CON INFRAESTRUCTURA PA

SELECT * FROM Infraestructura.POSTE PO
WHERE PO.ID_POSTE IN (73542,73541)

SELECT * FROM Infraestructura.PA
JOIN Infraestructura.DOM_TIPO_PA DTPA ON DTPA.ID_TIPO_PA = PA.ID_TIPO_PA
WHERE PA.ID_PA IN (73542,73541)

SELECT * FROM RED.TERMINAL T
WHERE T.ID_PROYECTO = 71607