--Fecha 20/02/2023
--Migraciones
--Source01
SELECT U.ID_PREDIAL, U.ID_CTO_PREASIGNADA, T.CODIGO AS CODIGOCTO, 
MAX(U.FECHA_ALTA) AS FECHA_CREACION, MAX(U.FECHA_ACT) AS FECHA_ACTUALIZACION
--MAX(U.FECHA_ACT) AS FECHA_ACTUALIZACION_UIP
FROM [CARTOGRAFIA].[UIP] U
JOIN [RED].[TERMINAL] T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA
WHERE (U.CH_COMPLEMENTO_VERTICAL_3 <> 'Adicional CMS' OR U.CH_COMPLEMENTO_VERTICAL_3 IS NULL)
GROUP BY U.ID_PREDIAL, U.ID_CTO_PREASIGNADA, T.CODIGO

--Source02
SELECT PR.ID_PREDIAL, DP.ID_DEPARTAMENTO AS CODIGO_DEPARTAMENTO, DP.NOMBRE AS NOMBRE_DEPARTAMENTO, PV.ID_PROVINCIA AS CODIGO_PROVINCIA,
        PV.NOMBRE AS NOMBRE_PROVINCIA, DS.ID_DISTRITO AS CODIGO_DISTRITO, DS.NOMBRE AS NOMBRE_DISTRITO,
        PR.INFORMACION_ADICIONAL AS URBANIZACION,
        TV.ABREVIATURA AS TIPO_VIA, V.NOMBRE AS NOMBRE_VIA, 
        PR.NUMERO AS NUMERO_PREDIO, PR.INFORMACION_ADICIONAL,
        PR.Shape.STX AS X, PR.Shape.STY AS Y, PR.FECHA_ALTA AS FECHA_CREACION, PR.FECHA_ACT AS FECHA_ACTUALIZACION
        FROM [CARTOGRAFIA].[PREDIAL] PR
        LEFT JOIN [CARTOGRAFIA].[VIA] V ON V.ID_VIA = PR.ID_VIA
        LEFT JOIN [CARTOGRAFIA].[DISTRITO] DS ON DS.ID_DISTRITO = PR.ID_DISTRITO
        LEFT JOIN [CARTOGRAFIA].[PROVINCIA] PV ON PV.ID_PROVINCIA = DS.ID_PROVINCIA
        LEFT JOIN [CARTOGRAFIA].[DEPARTAMENTO] DP ON DP.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO
        LEFT JOIN [CARTOGRAFIA].[DOM_TIPO_VIA] TV ON TV.ID_TIPO_VIA = V.ID_TIPO_VIA
		
		
--Horizontales
--Source01
SELECT U.ID_PREDIAL, U.ID_CTO_PREASIGNADA, T.CODIGO AS CODIGOCTO, 
--MAX(U.FECHA_ACT) AS FECHA_ACTUALIZACION_UIP
MAX(U.FECHA_ALTA) AS FECHA_CREACION, MAX(U.FECHA_ACT) AS FECHA_ACTUALIZACION
FROM [CARTOGRAFIA].[UIP] U
JOIN [RED].[TERMINAL] T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA
JOIN [Red].[PROYECTO] PR ON T.ID_PROYECTO =  PR.ID_PROYECTO
WHERE U.ID_CTO_PREASIGNADA IS NOT NULL
AND PR.ID_ESTADO_PROYECTO in (4,6) AND T.ID_CLASIFICACION_TERMINAL = 1001 
AND (U.CH_COMPLEMENTO_VERTICAL_3 <> 'Adicional CMS' OR U.CH_COMPLEMENTO_VERTICAL_3 IS NULL)
GROUP BY U.ID_PREDIAL, U.ID_CTO_PREASIGNADA, T.CODIGO

--Source02
SELECT PR.ID_PREDIAL, DP.ID_DEPARTAMENTO AS CODIGO_DEPARTAMENTO, DP.NOMBRE AS NOMBRE_DEPARTAMENTO, PV.ID_PROVINCIA AS CODIGO_PROVINCIA,
        PV.NOMBRE AS NOMBRE_PROVINCIA, DS.ID_DISTRITO AS CODIGO_DISTRITO, DS.NOMBRE AS NOMBRE_DISTRITO,
        PR.INFORMACION_ADICIONAL AS URBANIZACION,
        TV.ABREVIATURA AS TIPO_VIA, V.NOMBRE AS NOMBRE_VIA, 
        PR.NUMERO AS NUMERO_PREDIO, PR.Shape.STX AS X, PR.Shape.STY AS Y, PR.FECHA_ALTA AS FECHA_CREACION, PR.FECHA_ACT AS FECHA_ACTUALIZACION
        FROM [CARTOGRAFIA].[PREDIAL] PR
        LEFT JOIN [CARTOGRAFIA].[VIA] V ON V.ID_VIA = PR.ID_VIA
        LEFT JOIN [CARTOGRAFIA].[DISTRITO] DS ON DS.ID_DISTRITO = PR.ID_DISTRITO
        LEFT JOIN [CARTOGRAFIA].[PROVINCIA] PV ON PV.ID_PROVINCIA = DS.ID_PROVINCIA
        LEFT JOIN [CARTOGRAFIA].[DEPARTAMENTO] DP ON DP.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO
        LEFT JOIN [CARTOGRAFIA].[DOM_TIPO_VIA] TV ON TV.ID_TIPO_VIA = V.ID_TIPO_VIA

--Verticales
--Source01
SELECT CAST(U.ID_UIP AS int) AS ID_UIP , U.ID_PREDIAL AS IDPREDIAL , U.ID_CTO_PREASIGNADA AS IDCTO ,T.CODIGO AS CODIGOCTO, DP.ID_DEPARTAMENTO, DP.NOMBRE AS DEPARTAMENTO, PV.ID_PROVINCIA,
        PV.NOMBRE AS PROVINCIA, DS.ID_DISTRITO, DS.NOMBRE AS DISTRITO,
        PR.INFORMACION_ADICIONAL AS URBANIZACION,
        TV.ABREVIATURA AS TIPO_VIA, V.NOMBRE AS NOMBRE_VIA,
        PR.NUMERO AS NUMERO_PREDIAL,
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <> ' ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_1 ELSE
COMPLEMENTO_VERTICAL_1
END AS PISO,
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <> ' ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_2 ELSE
COMPLEMENTO_VERTICAL_2
END AS INTERIOR,
        U.COMPLEMENTO_HORIZONTAL AS BLOQUE ,
        PR.Shape.STX AS X, PR.Shape.STY AS Y,
        U.FECHA_ALTA AS FECHA_CREACION, U.FECHA_ACT AS FECHA_ACTUALIZACION
        FROM [CARTOGRAFIA].[UIP] U
        JOIN [CARTOGRAFIA].[PREDIAL] PR ON PR.ID_PREDIAL = U.ID_PREDIAL
        JOIN [CARTOGRAFIA].[VIA] V ON V.ID_VIA = PR.ID_VIA
        JOIN [CARTOGRAFIA].[DISTRITO] DS ON DS.ID_DISTRITO = PR.ID_DISTRITO
        JOIN [CARTOGRAFIA].[PROVINCIA] PV ON PV.ID_PROVINCIA = DS.ID_PROVINCIA
        JOIN [CARTOGRAFIA].[DEPARTAMENTO] DP ON DP.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO
        JOIN [CARTOGRAFIA].[DOM_TIPO_VIA] TV ON TV.ID_TIPO_VIA = V.ID_TIPO_VIA
        JOIN [RED].[TERMINAL] T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA
        JOIN [Red].[PROYECTO] PY ON T.ID_PROYECTO = PY.ID_PROYECTO
        WHERE U.ID_CTO_PREASIGNADA IS NOT NULL
        AND (U.CH_COMPLEMENTO_VERTICAL_3 <> 'Adicional CMS' OR U.CH_COMPLEMENTO_VERTICAL_3 IS NULL)
        AND PY.ID_ESTADO_PROYECTO in (4,6) AND T.ID_CLASIFICACION_TERMINAL = 1001