SELECT SUBSTRING(TERMINAL.CODIGO,1,2) AS l, 
		SUBSTRING(SITE_HOLDER.CODIGO, 1,2) AS r,
        TERMINAL.ID_TERMINAL,
        TERMINAL.CODIGO,
        SITE_HOLDER.ID_SITE_HOLDER,
        SITE_HOLDER.CODIGO
FROM [Red].[TERMINAL],[Infraestructura].[SITE_HOLDER]
JOIN TIPO_SITE ON TIPO_SITE.ID_TIPO_SITE = SITE_HOLDER.ID_TIPO_SITE
WHERE l = r AND TIPO_SITE.NOMBRE ='Oficina Central' --1002