--- SCRIPT REPORTE DE DEP - PROV - DISTR - SITEHOLDER
SELECT DE.NOMBRE AS DEPARTAMENTO,PV.NOMBRE AS PROVINCIA,DI.NOMBRE AS DISTRITO,
DI.ID_DISTRITO AS UBIGEO,SI.CODIGO,SI.NODO FROM Cartografia.DISTRITO DI
INNER JOIN Infraestructura.SITE_HOLDER SI ON SI.Shape.STIntersects(DI.Shape)=1
JOIN Cartografia.PROVINCIA PV ON PV.ID_PROVINCIA = DI.ID_PROVINCIA
JOIN Cartografia.DEPARTAMENTO DE ON DE.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO
WHERE SI.ID_TIPO_SITE = 1002
--**********************************************************************************************************

-- REPORTE DE UIP - TOTAL DE CTO PREASIGNADOS Y NO PREASIGNADOS CON SUS UIP, PREDIOS  --> 614 220
-- EN LA COLUMNA ID_CTO_PREASIGNADO LOS QUE TENGAS EL LLENO EL REGISTRO CON LOS
-- ID_TERMINALES , SIGNIFICA QUE ESTAN PREASIGNADOS-
-- LOS CTO QUE TENGAN NULL SUS REGISTROS SIGNIFICARÁ QUE NO ESTAN PREASIGNADAS

SELECT 
U.ID_UIP,U.ID_PREDIAL,TR.ID_TERMINAL,TR.CODIGO,EP.NOMBRE AS ESTADO,PR.ID_ESTADO_PROYECTO,U.ID_CTO_PREASIGNADA ,
CASE 
	WHEN U.ID_CTO_PREASIGNADA IS NOT NULL THEN 'CT0 PREASIGNADAS'
	WHEN U.ID_CTO_PREASIGNADA IS NULL THEN 'CT0 SIN PREASIGNAR'
END AS COMENTARIO_NTTDATA
FROM RED.TERMINAL TR
LEFT JOIN Cartografia.UIP U ON U.ID_CTO_PREASIGNADA = TR.ID_TERMINAL
LEFT JOIN Red.PROYECTO pr on pr.ID_PROYECTO = tr.ID_PROYECTO
LEFT JOIN RED.DOM_ESTADO_PROYECTO EP ON EP.ID_ESTADO_PROYECTO = PR.ID_ESTADO_PROYECTO
WHERE TR.ID_CLASIFICACION_TERMINAL = 1001 --CTO
-- PARA REALIZAR UN FILTRADO POR LISTA DESCOMENTAR LA LINEA DE ABAJO
--AND TR.CODIGO IN ('CVG3280209', .................,'CVG3280210')
--****************************************************************************************************************

-- REPORTE CALCULA CUANTAS UIP TIENE ASIGNADO UNA CTO , SI EL VALOR DE CONTADOR ES = 0
-- SIGNIFICARÁ NO TIENE UIP ASIGNADOS 
SELECT 
TR.CODIGO,COUNT(ID_CTO_PREASIGNADA) AS CONTADOR
FROM RED.TERMINAL TR
LEFT JOIN Cartografia.UIP U ON U.ID_CTO_PREASIGNADA = TR.ID_TERMINAL
where tr.CODIGO = 'HIG3211708'
GROUP BY TR.CODIGO

SELECT * FROM RED.TERMINAL T WHERE T.CODIGO = 'HIG3211708'
SELECT * FROM Cartografia.UIP U WHERE U.ID_CTO_PREASIGNADA = 67759

SELECT * FROM RED.TERMINAL TR
JOIN Cartografia.UIP U ON U.ID_CTO_PREASIGNADA = TR.ID_TERMINAL
WHERE tr.CODIGO = 'HIG3211708'

--*******************************************************************************************************************

-- REPORTE DE CTO ZA Y SM
-- TODASL LAS CTO DE SAN MIGUEL Y ZARATE --- TOTAL --> 4700  / CON EL FILTRO DEL FICHERO DONDE APARECE SA
SELECT TR.ID_TERMINAL,TR.CODIGO FROM RED.TERMINAL TR
WHERE TR.ID_CLASIFICACION_TERMINAL = 1001
AND (SUBSTRING(TR.CODIGO, 1, 2) = 'ZA' OR SUBSTRING(TR.CODIGO, 1, 2) = 'SM')
-- DESCOMENTAR PARA AGREGAR UN LISTA DE REGISTROS
/*D TR.CODIGO IN (
'SMG3131501'
,'SMG3131502'
,'SMG3161301'
,'SMG3061502')*/

--- REPORTE DE LOS ESTADOS DE BORNES DE LA CTO
SELECT 
borne.id_borne,
terminal.CODIGO,
divisor.id_divisor,
borne.id_estado_ocupacion
FROM [Red].[BORNE] left join [Red].divisor on borne.id_divisor = divisor.id_divisor 
left join red.TERMINAL on divisor.id_terminal = terminal.id_terminal
where borne.id_estado_ocupacion = 1001  -- 1001 = OCUPADO / 1002 = RESERVADOS


--- ACTUALIZACION DE BORNES
--CONSIDERACIONES --> SE DEBE REALIZAR UN BACKUP DE LA TABLAD DE BORNE COMO CONTINGENCIA

-- PASO 1 -REALIZAR EL FILTRADO POR EL ID_BORNE DEL FICHERO PROPORCIONADO POR JAVIER
SELECT * FROM RED.BORNE BR
-- DESCOMENTAR PARA REALIZAR UN BUSQUEDA POR FILTRO DE LISTA DE CMS
--WHERE BR.ID_BORNE IN (500001,500002)

-- PASO 2 - REALIZAR EL UPDATE DE TODO LOS REGISTROS FILTRADO DE FICHERO CMS POR ID_BORNE
-- SE DEBE DE ACTUALIZAR TODOS LOS CAMPOS DEL LA TABLA BORNE , CONSERVANDO SOLO EL ID_BORNE

