SELECT TR.ID_TERMINAL,TR.CODIGO,U.ID_UIP,PR.ID_PREDIAL,Q.node AS NODO,Q.CODIGO,Q.DISTRITO,Q.UBIGEO,U.ID_CTO_PREASIGNADA AS CTO_PREASIGNADA FROM
(SELECT SI.CODIGO,SI.NODO AS node,DI.NOMBRE AS DISTRITO,DI.ID_DISTRITO AS UBIGEO FROM Cartografia.DISTRITO DI
INNER JOIN Infraestructura.SITE_HOLDER SI ON SI.Shape.STIntersects(DI.Shape)=1
JOIN Cartografia.PROVINCIA PV ON PV.ID_PROVINCIA = DI.ID_PROVINCIA
JOIN Cartografia.DEPARTAMENTO DE ON DE.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO
WHERE SI.ID_TIPO_SITE = 1002) as Q , red.TERMINAL TR
JOIN Cartografia.UIP U ON U.ID_CTO_PREASIGNADA = TR.ID_TERMINAL
JOIN Cartografia.PREDIAL PR ON PR.ID_PREDIAL = U.ID_PREDIAL
WHERE SUBSTRING(TR.CODIGO,1,2)= Q.node
AND PR.ID_PREDIAL = 5868375  

AND Q.node = 'HI' -- NODOS FILTRAR
AND TR.CODIGO IN (
'HIG3211708'
,'HIG3211801'
,'HIG3211707'
,'HIG3211701'
,'HIG3211702'
,'HIG3211703'
,'HIG3211704'
,'HIG3211705'
,'HIG3211706'
,'SPG3201307'
,'SPG3201308')


SELECT * FROM Cartografia.UIP