
SELECT DISTINCT
PR.ID_PROYECTO,
PR.CODIGO,
DEP.NOMBRE,
T.ID_TERMINAL AS ID_TFO,
T.CODIGO AS CODIGO_TFO,
FT.NOMBRE AS FUNCION,
CT.NOMBRE AS TIPO,
Q.CODIGO_SITIO,
TCPA.ID_PA_ORIGEN,
TC.CODIGO,
Q.NUMERO,
Q.SENAL,
Q.CUENTA,
Q.ID_TRAMO_CABLE AS ID_TRAMO_ORIGEN

--TC.CODIGO AS CODIGO_TRAMO_DE_ORIGEN
FROM (SELECT FR.ID_TRAMO_CABLE,FR.NUMERO,FR.CUENTA,FR.SENAL,FR.CODIGO_SITIO, 
ROW_NUMBER() OVER(PARTITION BY FR.NUMERO ORDER BY FR.NUMERO) NumeroFila
FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE IN (547985)
AND FR.CUENTA IS NOT NULL 
GROUP BY FR.NUMERO,FR.CUENTA,FR.SENAL,FR.ID_TRAMO_CABLE,FR.CODIGO_SITIO
) AS Q
,
Infraestructura.PA PA,
RED.TRAMO_CABLE_PA TCPA,
RED.TRAMO_DE_CABLE TC,
RED.TERMINAL T
JOIN RED.DOM_FUNCION_TERMINAL FT ON FT.ID_FUNCION_TERMINAL = T.ID_FUNCION_TERMINAL
JOIN RED.DOM_CLASIFICACION_TERMINAL CT ON CT.ID_CLASIFICACION_TERMINAL = T.ID_CLASIFICACION_TERMINAL
JOIN RED.PROYECTO PR ON PR.ID_PROYECTO = T.ID_PROYECTO
JOIN RED.DOM_ESTADO_PROYECTO DEP ON DEP.ID_ESTADO_PROYECTO = PR.ID_ESTADO_PROYECTO
WHERE ((PA.ID_PA = T.ID_PA) AND (TCPA.ID_PA_ORIGEN = PA.ID_PA)) 
AND (TC.ID_TRAMO_CABLE = TCPA.ID_TRAMO_CABLE) 
AND T.ID_TERMINAL = 169275 --176187  


SELECT * FROM RED.FIBRA


 -- NUMERO DE LA FIBRA DE ORIGEN / CABLE LOGICO ORIGEN --547985
SELECT FR.ID_TRAMO_CABLE,FR.NUMERO,FR.CUENTA,FR.SENAL,FR.CODIGO_SITIO, 
ROW_NUMBER() OVER(PARTITION BY FR.NUMERO ORDER BY FR.NUMERO) NumeroFila
FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE IN (547985)
AND FR.CUENTA IS NOT NULL 
GROUP BY FR.NUMERO,FR.CUENTA,FR.SENAL,FR.ID_TRAMO_CABLE,FR.CODIGO_SITIO


 -- NUMERO DE LA FIBRA DE DESTINO / CABLE LOGICO DESTINO --547986
SELECT FR.ID_TRAMO_CABLE,FR.NUMERO,FR.CUENTA,FR.SENAL,FR.CODIGO_SITIO, 
ROW_NUMBER() OVER(PARTITION BY FR.NUMERO ORDER BY FR.NUMERO) NumeroFila
FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE IN (547986)
AND FR.CUENTA IS NOT NULL 
GROUP BY FR.NUMERO,FR.CUENTA,FR.SENAL,FR.ID_TRAMO_CABLE,FR.CODIGO_SITIO

SELECT FR.ID_TRAMO_CABLE,FR.NUMERO,FR.CUENTA,FR.SENAL,FR.CODIGO_SITIO, 
ROW_NUMBER() OVER(PARTITION BY FR.NUMERO ORDER BY FR.NUMERO) NumeroFila
FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE IN (551885)
AND FR.CUENTA IS NOT NULL 
GROUP BY FR.NUMERO,FR.CUENTA,FR.SENAL,FR.ID_TRAMO_CABLE,FR.CODIGO_SITIO


--TERMINAL 
SELECT * FROM RED.DIVISOR DI
WHERE DI.ID_DIVISOR IN ( 164180 , 164179)




-- sacar DATOS DE CODIGO TRAMO DE DESTINO -- FALTA SACAR PS01 DE TRAMO DE CABLE
SELECT DI.ID_DIVISOR,DI.CODIGO,TC.CODIGO,TCPA.ID_PA_DESTINO,TC.ID_TRAMO_CABLE FROM RED.TERMINAL TER
JOIN RED.DIVISOR DI ON DI.ID_TERMINAL= TER.ID_TERMINAL
JOIN Infraestructura.PA PA ON PA.ID_PA = TER.ID_PA
JOIN RED.TRAMO_CABLE_PA TCPA ON TCPA.ID_PA_DESTINO = PA.ID_PA
JOIN RED.TRAMO_DE_CABLE TC ON TC.ID_TRAMO_CABLE = TCPA.ID_TRAMO_CABLE
WHERE TER.ID_TERMINAL = 176187
AND TC.ID_TRAMO_CABLE = 547985





SELECT * FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE = 547985
AND FR.CUENTA IS NOT NULL








SELECT * FROM RED.TRAMO_DE_CABLE TC
JOIN RED.FIBRA FI ON FI.ID_TRAMO_CABLE = TC.ID_TRAMO_CABLE
JOIN Infraestructura.PA PA ON PA.ID_PA = 
WHERE TC.ID_TRAMO_CABLE = 542140
AND FI.SENAL = 'SMG302D06'


SELECT * FROM RED.TERMINAL T
WHERE T.ID_TERMINAL = 168913


--- 
SELECT * FROM RED.TRAMO_CABLE_PA TCPA
JOIN Infraestructura.PA PA ON PA.ID_PA = TCPA.ID_PA_ORIGEN
WHERE TCPA.ID_TRAMO_CABLE = 542140


SELECT * FROM RED.DOM_ESTADO_PROYECTO


select * from red.PROYECTO pro
where pro.CODIGO = '279172875359'

SELECT * FROM RED.DOM_TIPO_PUERTO


SELECT 
                        --P.[$node_id_EFFB4BE17AEC4EB9BB2EA42858046CD0] AS idNode,
                        P.ID_PUERTO,
                        P.ID_EQUIPO,
                        P.ID_TIPO_EQUIPO,
                        P.ID_PROYECTO_RESERVA AS idProyectoReserva,
                        P.ID_TIPO_EQUIPO,
                        P.CODIGO,
                        P.NUMERO AS puerto,
                        --F.[$from_id_E330DA25D3FB41828646CE2476ADF394] AS idFrom,
                       -- F.[$to_id_05B35385E2774AEB9B76D97464B95145] AS idTo,
                        F.ID_TRAMO_CABLE,
                        F.ID_TIPO_FIBRA,
                        F.NUMERO AS fibra,
                        F.CUENTA AS cuenta,
                        F.SENAL AS senal,
                        D.CODIGO AS codigoDivisor,
                        D.ID_TOPOLOGIA_RED AS nivelDivisor,
                        D.ID_TIPO_DIVISOR AS tipoDivisor,
                        C.CODIGO AS codigoCable
                        FROM Red.PUERTO P
                        LEFT JOIN Red.FIBRA F ON P.$node_id = F.$to_id  
                        LEFT JOIN RED.DIVISOR D ON P.ID_EQUIPO = D.ID_DIVISOR
                        LEFT JOIN RED.TRAMO_DE_CABLE C ON F.ID_TRAMO_CABLE = C.ID_TRAMO_CABLE
                        WHERE P.ID_TERMINAL = 176187 
						ORDER BY P.ID_PUERTO


SELECT
P.$node_id AS idNode,                       
P.ID_PUERTO,                        
P.ID_EQUIPO,                        
P.ID_TIPO_EQUIPO,                        
P.ID_PROYECTO_RESERVA AS idProyectoReserva,                        
P.ID_TIPO_PUERTO,                        
P.CODIGO,                        
P.NUMERO AS puerto,                        
F.$from_id AS idFrom,                        
F.$to_id AS idTo,                        
F.ID_TRAMO_CABLE,                        
D.ID_TOPOLOGIA_RED AS nivelDivisor,                        
D.ID_TIPO_DIVISOR AS tipoDivisor,                        
C.CODIGO AS codigoCable                        
FROM Red.PUERTO P                        
LEFT JOIN Red.FIBRA F ON P.$node_id = F.$to_id                         
LEFT JOIN Red.DIVISOR D ON P.ID_EQUIPO = D.ID_DIVISOR                         
LEFT JOIN Red.TRAMO_DE_CABLE C ON F.ID_TRAMO_CABLE = C.ID_TRAMO_CABLE                         
WHERE P.ID_TERMINAL = 176187 ORDER BY P.ID_PUERTO

