SELECT 
T.ID_TERMINAL,
T.CODIGO,
--T.ID_FUNCION_TERMINAL,
FT.NOMBRE AS FUNCION_TERMINAL,
--.ID_TIPO_TERMINAL,
TT.NOMBRE AS TIPO_TERMINAL,
DI.ID_DIVISOR,
DI.CODIGO,
--DI.ID_TIPO_DIVISOR,
TDI.NOMBRE,
DI.CODIGO,
DI.NUMERO_PUERTOS,
PR.ID_PROYECTO,
PR.CODIGO
FROM RED.TERMINAL T
JOIN RED.DOM_FUNCION_TERMINAL FT ON FT.ID_FUNCION_TERMINAL = T.ID_FUNCION_TERMINAL
JOIN RED.DOM_TIPO_TERMINAL TT ON TT.ID_TIPO_TERMINAL = T.ID_TIPO_TERMINAL
JOIN RED.DIVISOR DI ON DI.ID_TERMINAL = T.ID_TERMINAL
JOIN RED.DOM_TIPO_DIVISOR TDI ON TDI.ID_TIPO_DIVISOR = DI.ID_TIPO_DIVISOR
JOIN RED.PROYECTO PR ON PR.ID_PROYECTO = T.ID_PROYECTO

