SELECT TR.ID_TERMINAL,TR.CODIGO,DI.CODIGO,DI.ID_TOPOLOGIA_RED,BR.LINE_ID,EO.NOMBRE,U.ID_UIP FROM RED.TERMINAL TR
JOIN RED.DIVISOR DI ON DI.ID_TERMINAL = TR.ID_TERMINAL
JOIN RED.BORNE BR ON BR.ID_DIVISOR = DI.ID_DIVISOR
JOIN RED.DOM_ESTADO_OCUPACION EO ON EO.ID_ESTADO_OCUPACION = BR.ID_ESTADO_OCUPACION
JOIN Cartografia.UIP U ON U.ID_UIP = BR.ID_UIP
WHERE BR.LINE_ID ='PER.TDP.1676579771951'