SELECT T.CODIGO,U.ID_CTO_PREASIGNADA,U.ID_UIP,PR.ID_ESTADO_PROYECTO , DEP.NOMBRE FROM RED.TERMINAL T
JOIN Cartografia.UIP U ON U.ID_CTO_PREASIGNADA = T.ID_TERMINAL
JOIN RED.PROYECTO PR ON PR.ID_PROYECTO = T.ID_PROYECTO
JOIN RED.DOM_ESTADO_PROYECTO DEP ON DEP.ID_ESTADO_PROYECTO = PR.ID_ESTADO_PROYECTO
WHERE T.ID_CLASIFICACION_TERMINAL = 1001 

SELECT * FROM Cartografia.UIP