SELECT distinct 
CTO.ID_TERMINAL AS CTO_ID_TERMINAL, 
CTO.CODIGO AS CTO_CODIGO, 
SUBSTRING(CTO.CODIGO, 1, 6) AS Prefix6,
DIVICAU.ID_TERMINAL AS DIVICAU_ID_TERMINAL, 
DIVICAU.CODIGO AS DIVICAU_CODIGO,
SITE_HOLDER.ID_SITE_HOLDER , 
SITE_HOLDER.CODIGO AS SITE_HOLDER_CODIGO , 
SUBSTRING(CTO.CODIGO, 1, 2) AS Prefix2
FROM [Red].[TERMINAL] AS CTO
JOIN [Red].[TERMINAL] AS DIVICAU ON Prefix6 =  DIVICAU.CODIGO
JOIN Infraestructura.SITE_HOLDER ON SITE_HOLDER.NODO = SUBSTRING(CTO.CODIGO, 1, 2)
WHERE CTO.ID_CLASIFICACION_TERMINAL = 1001 AND DIVICAU.ID_CLASIFICACION_TERMINAL = 1002  AND SITE_HOLDER.ID_TIPO_SITE = 1002



SELECT   distinct        
T.ID_TERMINAL AS CTO,        
SUBSTRING(T.CODIGO,3,LEN(T.CODIGO)) AS DIVICAO,        
NODO as NODO,SUBSTRING(T.CODIGO,1,6) AS CTO_KEY  -- LLAVE
FROM

(SELECT S.NODO,S.ID_SITE_HOLDER,S.CODIGO 
	FROM       Red.PUERTO  p    
	JOIN Red.PUERTO_ODF PO ON P.ID_EQUIPO = PO.ID_PUERTO_ODF    
	JOIN Red.ODF O ON PO.ID_ODF = O.ID_ODF    
	JOIN Infraestructura.SITE_HOLDER S ON O.ID_SITE_HOLDER = S.ID_SITE_HOLDER   ) 

AS NODO , [Red].[TERMINAL] T    
WHERE SUBSTRING(T.CODIGO, 1, 2) = NODO    AND T.ID_CLASIFICACION_TERMINAL = 1002