SELECT 
CAST(U.ID_UIP AS int) AS ID_UIP , 
U.ID_PREDIAL AS IDPREDIAL , 
U.ID_CTO_PREASIGNADA AS IDCTO ,
T.CODIGO AS CODIGOCTO, 
DP.ID_DEPARTAMENTO, 
DP.NOMBRE AS DEPARTAMENTO, 
PV.ID_PROVINCIA,         
PV.NOMBRE AS PROVINCIA, 
DS.ID_DISTRITO, 
DS.NOMBRE AS DISTRITO,         
PR.INFORMACION_ADICIONAL AS URBANIZACION,         
TV.ABREVIATURA AS TIPO_VIA, V.NOMBRE AS NOMBRE_VIA,         
PR.NUMERO AS NUMERO_PREDIAL,                  
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <>   '  ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_1 ELSE 
COMPLEMENTO_VERTICAL_1 
END AS PISO,       
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <>   '  ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_2 ELSE 
COMPLEMENTO_VERTICAL_2         
END AS INTERIOR,         
U.COMPLEMENTO_HORIZONTAL AS BLOQUE ,         
PR.Shape.STX AS X, PR.Shape.STY AS Y,         
U.FECHA_ALTA AS FECHA_CREACION, 
U.FECHA_ACT AS FECHA_ACTUALIZACION         
FROM [CARTOGRAFIA].[UIP] U         
JOIN [CARTOGRAFIA].[PREDIAL] PR ON PR.ID_PREDIAL = U.ID_PREDIAL         
JOIN [CARTOGRAFIA].[VIA] V ON V.ID_VIA = PR.ID_VIA         
JOIN [CARTOGRAFIA].[DISTRITO] DS ON DS.ID_DISTRITO = PR.ID_DISTRITO         
JOIN [CARTOGRAFIA].[PROVINCIA] PV ON PV.ID_PROVINCIA = DS.ID_PROVINCIA         
JOIN [CARTOGRAFIA].[DEPARTAMENTO] DP ON DP.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO         
JOIN [CARTOGRAFIA].[DOM_TIPO_VIA] TV ON TV.ID_TIPO_VIA = V.ID_TIPO_VIA         
JOIN [RED].[TERMINAL] T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA         
JOIN [Red].[PROYECTO] PY ON T.ID_PROYECTO = PY.ID_PROYECTO         
WHERE U.ID_CTO_PREASIGNADA IS NOT NULL         
AND (U.CH_COMPLEMENTO_VERTICAL_3 <>  'Adicional CMS' OR U.CH_COMPLEMENTO_VERTICAL_3 IS NULL)      
AND PY.ID_ESTADO_PROYECTO = 4 AND T.ID_CLASIFICACION_TERMINAL = 1001
AND T.ID_TERMINAL = 182413

SELECT * FROM RED.DOM_CLASIFICACION_TERMINAL
SELECT * FROM Cartografia.VIA

SELECT * FROM Cartografia.DOM_TIPO_VIA

-- SCRIPT Reporte ODF_PUERTO_ODF_SITEHOLDER  ---PG_CRODF01
SELECT * FROM RED.ODF O
JOIN RED.PUERTO_ODF PO ON PO.ID_ODF = O.ID_ODF 
--JOIN Infraestructura.SITE_HOLDER SI ON SI.ID_SITE_HOLDER = O.ID_SITE_HOLDER
WHERE O.CODIGO = 'PG_CRODF01' -- SE DEBE DELIMITAR MAS EL REPORTE PARA TRAER -- MODULO BANDEJA PUERTO NOMBRE COMPLETO CON LA CONCATENACION LOS 3 CAMPOS


SELECT * FROM RED.DOM_FABRICANTE
SELECT * FROM RED.DOM_TIPO_ODF
SELECT * FROM RED.DOM_TIPO_BASTIDOR

SELECT * FROM RED.TRAMO_DE_CABLE
SELECT * FROM Infraestructura.SITE_HOLDER ST
WHERE ST.CODIGO LIKE '%LINCE%'




SELECT * FROM RED.PUERTO  -- ID_EQUIPO = 228812
SELECT * FROM RED.PUERTO_ODF PODF
WHERE PODF.ID_PUERTO_ODF = 228812

SELECT * FROM RED.TERMINAL TR
JOIN RED.DIVISOR DI ON DI.ID_TERMINAL = TR.ID_TERMINAL
JOIN RED.BORNE BR ON BR.ID_DIVISOR = DI.ID_DIVISOR
WHERE TR.CODIGO = 'SMG3131501'

SELECT * FROM Cobertura.CTO_AREA
SELECT * FROM Cobertura.EDIFICIO_AREA
SELECT * FROM Cartografia.PREDIAL

SELECT * FROM Infraestructura.DOM_TIPO_SITUACION

SELECT * FROM RED.DOM_ESTADO_PROYECTO
SELECT * FROM RED.PROYECTO
SELECT * FROM Infraestructura.POSTE
SELECT * FROM Infraestructura.PA
SELECT * FROM Infraestructura.DOM_TIPO_PA

--ACO.Shape.STAsText() AS COORDENADAS_ACOMETIDA
SELECT TR.Shape.STAsText() FROM RED.TERMINAL TR
WHERE TR.ID_CLASIFICACION_TERMINAL = 1001

SELECT * FROM RED.DOM_ESTADO_OCUPACION


SELECT * FROM Cartografia.PREDIAL
SELECT * FROM Cartografia.UIP
SELECT * FROM RED.DOM_TIPO_CABLE
SELECT * FROM RED.DOM_TIPO_RED
SELECT * FROM Infraestructura.SITE_HOLDER
SELECT * FROM Infraestructura.DOM_CLASIFICACION_SITE

SELECT SUBSTRING(VARCHAR,R.NORMALIZADO,2) FROM Cartografia.PREDIAL R


SELECT SUBSTRING(PR.NORMALIZADO,1,(CHARINDEX(',',PR.NORMALIZADO))-1) AS CODIGO_CALLE FROM Cartografia.PREDIAL PR  


SELECT * FROM CARTOGRAFIA.PREDIAL PR
JOIN Cartografia.UIP U ON U.ID_PREDIAL = PR.ID_PREDIAL
WHERE PR.ID_PREDIAL = 6408207 



SELECT TR.Shape.STAsText(),TR.CODIGO FROM Red.TERMINAL TR


SELECT * FROM RED.TERMINAL__ATTACH