-- vertical
SELECT CAST(U.ID_UIP AS int) AS ID_UIP , 
U.ID_PREDIAL AS IDPREDIAL , U.ID_CTO_PREASIGNADA AS IDCTO ,
T.CODIGO AS CODIGOCTO, DP.ID_DEPARTAMENTO, DP.NOMBRE AS DEPARTAMENTO, PV.ID_PROVINCIA,         
PV.NOMBRE AS PROVINCIA, DS.ID_DISTRITO, DS.NOMBRE AS DISTRITO,         
PR.INFORMACION_ADICIONAL AS URBANIZACION,         
TV.ABREVIATURA AS TIPO_VIA, V.NOMBRE AS NOMBRE_VIA,         
PR.NUMERO AS NUMERO_PREDIAL,                  
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <>   '  ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_1 
ELSE COMPLEMENTO_VERTICAL_1         
END AS PISO,       
CASE WHEN LTRIM(COMPLEMENTO_HORIZONTAL) <>   '  ' AND COMPLEMENTO_HORIZONTAL IS NOT NULL THEN CH_COMPLEMENTO_VERTICAL_2 
ELSE COMPLEMENTO_VERTICAL_2         
END AS INTERIOR,         
U.COMPLEMENTO_HORIZONTAL AS BLOQUE ,        
PR.Shape.STX AS X, PR.Shape.STY AS Y,         
U.FECHA_ALTA AS FECHA_CREACION, U.FECHA_ACT AS FECHA_ACTUALIZACION,
U.CH_COMPLEMENTO_VERTICAL_3,
PY.ID_ESTADO_PROYECTO,
T.ID_CLASIFICACION_TERMINAL
FROM [CARTOGRAFIA].[UIP] U         
JOIN [CARTOGRAFIA].[PREDIAL] PR ON PR.ID_PREDIAL = U.ID_PREDIAL         
JOIN [CARTOGRAFIA].[VIA] V ON V.ID_VIA = PR.ID_VIA         
JOIN [CARTOGRAFIA].[DISTRITO] DS ON DS.ID_DISTRITO = PR.ID_DISTRITO         
JOIN [CARTOGRAFIA].[PROVINCIA] PV ON PV.ID_PROVINCIA = DS.ID_PROVINCIA         
JOIN [CARTOGRAFIA].[DEPARTAMENTO] DP ON DP.ID_DEPARTAMENTO = PV.ID_DEPARTAMENTO         
JOIN [CARTOGRAFIA].[DOM_TIPO_VIA] TV ON TV.ID_TIPO_VIA = V.ID_TIPO_VIA         
JOIN [RED].[TERMINAL] T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA         
JOIN [Red].[PROYECTO] PY ON T.ID_PROYECTO = PY.ID_PROYECTO        
WHERE U.ID_CTO_PREASIGNADA IS NOT NULL      
AND (U.CH_COMPLEMENTO_VERTICAL_3 <> 'Adicional CMS' OR U.CH_COMPLEMENTO_VERTICAL_3 IS NULL)
AND PY.ID_ESTADO_PROYECTO = 4 AND T.ID_CLASIFICACION_TERMINAL = 1001
--AND V.NOMBRE IN ('INDEPENDENCIA','ROSA DE PEREZ LIENDO','MIRAMAR')
--AND DS.NOMBRE = 'SAN MIGUEL'
AND U.ID_UIP = 587599

SELECT * FROM Cartografia.VIA V
WHERE V.NORMALIZADO = 'CL INDEPENDENCIA'

SELECT  * FROM Cartografia.UIP U
WHERE U.ID_UIP = 292721

SELECT  * FROM Cartografia.UIP UIP
WHERE UIP.ID_UIP IN (
553123
,553129
,553131
,562207
,562252)

SELECT * FROM Cartografia.DISTRITO DI
WHERE DI.ID_DISTRITO = 150136

SELECT  * FROM RED.PUERTO_ODF ODF
JOIN red.DOM_ESTADO_OCUPACION EO ON EO.ID_ESTADO_OCUPACION = ODF.ID_ESTADO_OCUPACION
WHERE ODF.ID_ESTADO_OCUPACION = 1004 -- 1004 LIBRE

 ---PG_ZAODF01-03-07-01
select * from red.PUERTO_ODF where NOMBRE_COMPLETO LIKE 'PG_ZAODF01-03-07-01' 

SELECT * FROM Cartografia.DOM_USO_PREDIAL

