SELECT DISTINCT
T.ID_TERMINAL AS ID_TFO,
T.CODIGO AS CODIGO_TFO,
FT.NOMBRE AS FUNCION,
CT.NOMBRE AS TIPO,
FI.CODIGO_SITIO,
TC.ID_TRAMO_CABLE AS ID_TRAMO_ORIGEN,
TC.CODIGO AS CODIGO_TRAMO_DE_ORIGEN
FROM 
Infraestructura.PA PA,
RED.TRAMO_CABLE_PA TCPA,
RED.TRAMO_DE_CABLE TC,
RED.FIBRA FI,RED.TERMINAL T
JOIN RED.DOM_FUNCION_TERMINAL FT ON FT.ID_FUNCION_TERMINAL = T.ID_FUNCION_TERMINAL
JOIN RED.DOM_CLASIFICACION_TERMINAL CT ON CT.ID_CLASIFICACION_TERMINAL = T.ID_CLASIFICACION_TERMINAL
WHERE (PA.ID_PA = T.ID_PA AND TCPA.ID_PA_ORIGEN = PA.ID_PA) --AND (TC.ID_TRAMO_CABLE = TCPA.ID_TRAMO_CABLE) 
AND T.ID_TERMINAL = 176187  
AND FI.CUENTA IS NOT NULL
AND FI.CODIGO_SITIO = 'SJ-SAN JOSE'


SELECT * FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE = 547985




 -- NUMERO DE LA FIBRA DE ORIGEN / CABLE LOGICO ORIGEN
SELECT FR.ID_TRAMO_CABLE,FR.NUMERO,FR.CUENTA,FR.SENAL,FR.CODIGO_SITIO, 
ROW_NUMBER() OVER(PARTITION BY FR.NUMERO ORDER BY FR.NUMERO) NumeroFila
FROM RED.FIBRA FR
WHERE FR.ID_TRAMO_CABLE IN (547985)
AND FR.CUENTA IS NOT NULL 
GROUP BY FR.NUMERO,FR.CUENTA,FR.SENAL,FR.ID_TRAMO_CABLE,FR.CODIGO_SITIO