                            
            SUBSTR(T.FECHATXN, 1, 8) AS FECHATRANSAC,
            SUBSTR(T.FECHATXN, 9, 6) AS HORATRANSAC, 
            T.FECHASESION AS FECHASESION,
            T.FECHAABONO AS FECHAABONO,
            T.CODIGOMENSAJE AS CODIGOMENSAJE,
            (SELECT NOMBRE FROM MULTIUSO WHERE IDPADRE = 3748 AND VALOR = T.CODIGOMENSAJE) AS DESCODIGOMENSAJE,
            T.CODIGOFUNCION AS CODIGOFUNCION,
            (SELECT NOMBRE FROM MULTIUSO WHERE IDPADRE = 3717 AND VALOR = T.CODIGOFUNCION) AS DESCODIGOFUNCION,
            T.CODIGOACCION AS CODIGOACCION,
            (SELECT NOMBRE FROM MULTIUSO WHERE IDPADRE = 20974 AND VALOR = T.CODIGOACCION) AS DESCODIGOACCION,
            T.CODIGORAZON AS CODIGORAZON,
            (SELECT NOMBRE FROM MULTIUSO WHERE IDPADRE = 4339 AND VALOR = T.CODIGORAZON) AS DESCODIGORAZON,
            T.TIPOOPERACION AS TIPOTRANSACCION,
            (CASE WHEN T.IMPORTEBRUTO IS NOT NULL THEN TO_CHAR (T.IMPORTEBRUTO, 'FM9999999990.00')END) AS IMPORTETRANSACCION, --ImporteTransaccion
            (CASE WHEN T.COMISIONTOTAL IS NOT NULL THEN TO_CHAR (T.COMISIONTOTAL, 'FM9999999990.00')END) AS IMPORTECOMISIONTOTAL, --ImporteComisionTotal
            (CASE WHEN T.COMISIONEMISOR IS NOT NULL THEN TO_CHAR (T.COMISIONEMISOR, 'FM9999999990.00')END) AS IMPORTECOMISIONEMISOR, --ImporteComisionEmisor
            (CASE WHEN T.COMISIONADQ IS NOT NULL THEN TO_CHAR (T.COMISIONADQ, 'FM9999999990.00')END) AS IMPORTECOMISIONADQUIRENTE, --ImporteComisionAdquirente
            (CASE WHEN T.COMISIONNOAPLICEMISOR IS NOT NULL THEN TO_CHAR (T.COMISIONNOAPLICEMISOR, 'FM9999999990.00')END) AS IMPORTECOMISIONDEVOLUCION, --ImporteComisionDevolucion                  
            (CASE WHEN T.COMISIONAPLICA IS NOT NULL THEN TO_CHAR (T.COMISIONAPLICA, 'FM999990.00')END) AS IMPORTECOMISIONNOAPLICABLE, --ImporteComisionNoAplicable                            
            (CASE WHEN T.IMPORTEIGV IS NOT NULL THEN TO_CHAR (T.IMPORTEIGV, 'FM9999999990.00')END) AS IMPORTEIGV, --ImporteIGV      
            (CASE WHEN T.IMPORTENETO IS NOT NULL THEN TO_CHAR (T.IMPORTENETO, 'FM9999999990.00')END) AS IMPORTENETO, --ImporteNeto
            T.NUMEROCUENTA AS CUENTABANCARIA,
            T.ESTADO AS CODESTADOABONO,  
            (SELECT NOMBRE FROM MULTIUSO WHERE VALOR = T.ESTADO AND IDPADRE = T.IDESTADO) AS DESESTADOABONO,
             T.TIPOCAPTURA AS CODTIPOCAPTURA,
            (SELECT NOMBRE FROM MULTIUSO WHERE VALOR = T.TIPOCAPTURA AND IDPADRE = T.IDTIPOCAPTURA) AS DESTIPOCAPTURA,
             T.CODIGOCONTABLE AS CODIGOCONTABLE,
            --CC.DESCRIPCION AS DESCODIGOCONTABLE,
            (SELECT NOMBRE FROM MULTIUSO WHERE IDPADRE = 21722 AND VALOR = T.ORIGEN) AS ORIGENREGISTRO,
            --NVL(EP.TIPOREGISTRO, NVL (AN.TIPOREGISTRO, NVL (CPC.TIPOREGISTRO,''))) AS TIPOREGISTRO,
            T.NUMEROINCIDENCIA AS NROINCIDENCIA,
            (TO_CHAR(T.LOGFECHA,'YYYYMMDD')) AS FECHAMODIFICACION,
            T.IDORDENPAGO AS IDORDENPAGO,
            --CPC.INFORMACIONADICIONAL AS INFORMACIONADICIONAL,
            (PKG_COMUNES.SF_TIPOAUTENTICACION(T.DATOSPUNTOSERV)) AS TIPOAUTENTICACION,
            T.RESULTAUTIAD AS RESULTADOAUTENTICACION,
            T.NOMBREEMPPSV AS CODIGOSERVICIO,
            T.VALORIAD AS IAD,    
            --(NVL(CPC.INDICADORCONIGV, 'N')) AS INCLUYEIGVCP,  
            ---CPC.TIPOCARGOABONO AS TIPOOPERACION, 
            --PT.CODIGOPLAN AS CODPLANTARIFARIO,
            --PT.DESCRIPCIONPLAN AS DESPLANTARIFARIO, 
            T.CAPTURATRAN AS TIPCAPTRANSACCIONAL,
            T.CANALTRAN AS CANTRANSACCIONAL,
            T.PRODUCTOTRAN AS PROTRANSACCIONAL,
            --(CASE WHEN CPC.FECHAGENOPECONT IS NULL THEN '' ELSE TO_CHAR(CPC.FECHAGENOPECONT,'YYYYMMDD') END) AS FECHAAGENDADA, --FechaAgendada
            T.USUARIO AS USUARIOREGISTRO, --UsuarioRegistro
            (CASE WHEN T.COMISIONTOTAL IS NOT NULL THEN TO_CHAR (T.COMISIONTOTAL, 'FM9999999990.00')END) AS COMISIONCOMERCIO, --ComisionComercio
            T.NUMERORUC AS RUC, --RUC
            T.CODPROGCUOTASSI AS CODPROGRAMACSI, --CodProgramaCSI
            (CASE WHEN T.IMPCUOTASSI IS NOT NULL THEN TO_CHAR (T.IMPCUOTASSI, 'FM9999999990.00')END) AS IMPDESCONTADOCSI, --ImpDescontadoCSI
            T.SOURCE AS SOURCETARJETA, --SourceTarjeta