SELECT AN.OBJECTID
	,AN.ID_ANCLA as AN__ID_ANCLA
	,AN.ID_TIPO_ANCLA as AN__ID_TIPO_ANCLA
	,AN.ID_LOCALIZACION as AN__ID_LOCALIZACION
	,AN.ID_TIPO_PROPIEDAD as AN__ID_TIPO_PROPIEDAD
	,AN.ID_PROPIETARIO as AN__ID_PROPIETARIO
	,AN.ID_SITUACION as AN__ID_SITUACION
	,AN.ID_PROYECTO as AN__ID_PROYECTO
	,AN.OBSERVACION as AN__OBSERVACION
	,AN.FECHA_ALTA as AN__FECHA_ALTA
	,AN.FECHA_ACT as AN__FECHA_ACT
	,AN.Shape
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.ANCLA AN, Red.PROYECTO PR
WHERE AN.ID_PROYECTO = PR.ID_PROYECTO;
