SELECT CA.OBJECTID
	,CA.ID_CAMARA as CA__ID_CAMARA
	,CA.ID_TIPO_CAMARA as CA__ID_TIPO_CAMARA
	,CA.LONGITUD as CA__LONGITUD
	,CA.ANCHO as CA__ANCHO
	,CA.ALTURA as CA__ALTURA
	,CA.RUTA as CA__RUTA
	,CA.OBSERVACION2 as CA__OBSERVACION2
	,CA.ID_TIPO_PROPIEDAD as CA__ID_TIPO_PROPIEDAD
	,CA.ID_PROPIETARIO as CA__ID_PROPIETARIO
	,CA.ID_SITUACION as CA__ID_SITUACION
	,CA.ID_PROYECTO as CA__ID_PROYECTO
	,CA.ID_PA as CA__ID_PA
	,CA.OBSERVACION as CA__OBSERVACION
	,CA.FECHA_ALTA as CA__FECHA_ALTA
	,CA.FECHA_ACT as CA__FECHA_ACT
	,CA.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.CAMARA CA, Infraestructura.PA PA, Red.PROYECTO PR
WHERE CA.ID_PA = PA.ID_PA AND CA.ID_PROYECTO = PR.ID_PROYECTO;
