SELECT BD.OBJECTID
	,BD.ID_DERIVACION_BANCO_DUCTOS as BD__ID_DERIVACION_BANCO_DUCTOS
	,BD.OBSERVACION as BD__OBSERVACION
	,BD.ID_LOCALIZACION as BD__ID_LOCALIZACION
	,BD.ID_TIPO_PROPIEDAD as BD__ID_TIPO_PROPIEDAD
	,BD.ID_PROPIETARIO as BD__ID_PROPIETARIO
	,BD.ID_PROYECTO as BD__ID_PROYECTO
	,BD.ID_SITUACION as BD__ID_SITUACION
	,BD.ID_PA as BD__ID_PA
	,BD.FECHA_ALTA as BD__FECHA_ALTA
	,BD.FECHA_ACT as BD__FECHA_ACT
	,BD.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.DERIVACION_BANCO_DUCTOS BD, Infraestructura.PA PA, Red.PROYECTO PR
WHERE BD.ID_PA = PA.ID_PA AND BD.ID_PROYECTO = PR.ID_PROYECTO;
