CREATE VIEW [Cartografia].[V_DIRECCION] AS
SELECT DP.[ID_DEPARTAMENTO] codigoDepartamento, DP.[NOMBRE] nombreDepartamento
,PV.[ID_PROVINCIA] codigoProvincia, PV.[NOMBRE] nombreProvincia
,DS.[ID_DISTRITO] codigoDistrito ,DS.[NOMBRE] nombreDistrito
,MZ.[CODIGO] codigoManzana, MZ.[NOMBRE] nombreManzana
,TV.[ABREVIATURA] tipoVia
, V.[NOMBRE] nombreVia, V.NORMALIZADO codigoVia
,PR.[ID_PREDIAL] idPredial
,PR.NUMERO numero
,UP.NOMBRE usoPredial
,RA.[DESCRIPCION] refAtencion
--NO TENEMOS codURA
,T.ID_TERMINAL idTerminal,T.Codigo codCTOPreasignada, T.Shape.STX coordCTOX, T.Shape.STY coordCTOY, T.Piso pisoCTO
,U.[ID_UIP] homeId,U.[COMPLEMENTO_VERTICAL_1] piso,U.[COMPLEMENTO_VERTICAL_2] interior, U.[CLIENTE] codigoCliente
,U.[COMPLEMENTO_HORIZONTAL] bloque, U.[CH_COMPLEMENTO_VERTICAL_1] nombreCondominio,U.[CH_COMPLEMENTO_VERTICAL_2] edificioCondominio,U.[CH_COMPLEMENTO_VERTICAL_3] bloqueCondominio
FROM [Cartografia].[UIP] U
LEFT JOIN [Cartografia].[PREDIAL] PR ON PR.ID_PREDIAL = U.ID_PREDIAL
LEFT JOIN [Cartografia].[DOM_USO_PREDIAL] UP ON UP.ID_USO_PREDIAL = PR.ID_USO_PREDIAL
LEFT JOIN [Cartografia].[DOM_REFERENCIA_ATENCION] RA ON RA.[ID_REF_ATENCION] = PR.ID_REF_ATENCION
LEFT JOIN [Red].Terminal T ON T.ID_TERMINAL = U.ID_CTO_PREASIGNADA --AND T.ID_TIPO_TERMINAL BETWEEN 0 AND 10 -- IDTipoTerminal 1-10 --> CTOs
LEFT JOIN [Cartografia].[VIA] V ON V.[ID_VIA] = PR.[ID_VIA]
LEFT JOIN [Cartografia].[DOM_TIPO_VIA] TV ON TV.[ID_TIPO_VIA] = V.[ID_TIPO_VIA]
LEFT JOIN [Cartografia].[MANZANA] MZ ON (PR.SHAPE).STIntersects(MZ.SHAPE)=1
LEFT JOIN [Cartografia].[DISTRITO] DS ON DS.[ID_DISTRITO] = PR.[ID_DISTRITO]
LEFT JOIN [Cartografia].[PROVINCIA] PV ON PV.[ID_PROVINCIA] = DS.[ID_PROVINCIA]
LEFT JOIN [Cartografia].[DEPARTAMENTO] DP ON DP.[ID_DEPARTAMENTO] = PV.[ID_DEPARTAMENTO];
