SELECT DI.OBJECTID
	,DI.ID_DISTRITO as DI__ID_DISTRITO
	,DI.ID_PROVINCIA as DI__ID_PROVINCIA
	,DI.NOMBRE as DI__NOMBRE
	,DI.CODIGO_POSTAL as DI__CODIGO_POSTAL
	,DI.Shape
	,PV.ID_PROVINCIA as PV__ID_PROVINCIA
	,PV.ID_DEPARTAMENTO as PV__ID_DEPARTAMENTO
	,PV.NOMBRE as PV__NOMBRE
	,PV.CODIGO_POSTAL as PV__CODIGO_POSTAL
FROM Cartografia.DISTRITO DI, Cartografia.PROVINCIA PV
WHERE DI.ID_PROVINCIA = PV.ID_PROVINCIA;
