SELECT CD.OBJECTID
	,CD.ID_AREA_DIVICAU as CD__ID_AREA_DIVICAU
	,CD.ID_TERMINAL as CD__ID_TERMINAL
	,CD.INDICADOR_BLOQUEO as CD__INDICADOR_BLOQUEO
	,CD.FECHA_ALTA as CD__FECHA_ALTA
	,CD.FECHA_ACT as CD__FECHA_ACT
	,CD.Shape
	,TR.FIBRAS_RESERVADAS as TR__FIBRAS_RESERVADAS
	,TR.FIBRAS_OCUPADAS as TR__FIBRAS_OCUPADAS
	,TR.FIBRAS_LIBRES as TR__FIBRAS_LIBRES
	,TR.FIBRAS_DEFECTUOSAS as TR__FIBRAS_DEFECTUOSAS
	,TR.FIBRAS_ASIGNADAS as TR__FIBRAS_ASIGNADAS
	,TR.RUTA as TR__RUTA
	,TR.OBSERVACION as TR__OBSERVACION
	,TR.OBSERVACION2 as TR__OBSERVACION2
	,TR.PISO as TR__PISO
	,TR.NUM_DIVISORES_1N as TR__NUM_DIVISORES_1N
	,TR.NUM_DIVISORES_2N as TR__NUM_DIVISORES_2N
	,TR.ID_PROYECTO as TR__ID_PROYECTO
	,TR.ID_FUNCION_TERMINAL as TR__ID_FUNCION_TERMINAL
	,TR.FECHA_ACT as TR__FECHA_ACT
	,TR.FECHA_ALTA as TR__FECHA_ALTA
	,TR.ID_PREDIAL as TR__ID_PREDIAL
	,TR.ID_PA as TR__ID_PA
	,TR.ID_TIPO_TERMINAL as TR__ID_TIPO_TERMINAL
	,TR.ID_CLASIFICACION_TERMINAL as TR__ID_CLASIFICACION_TERMINAL
	,TR.ID_TERMINAL as TR__ID_TERMINAL
	,TR.ID_TIPO_PROPIEDAD as TR__ID_TIPO_PROPIEDAD
	,TR.ID_PROPIETARIO as TR__ID_PROPIETARIO
	,TR.ID_SITUACION as TR__ID_SITUACION
	,TR.CODIGO as TR__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Cobertura.DIVICAU_AREA CD, Red.TERMINAL TR, Red.PROYECTO PR
WHERE CD.ID_TERMINAL = TR.ID_TERMINAL AND TR.ID_PROYECTO = PR.ID_PROYECTO;
