SELECT DU.OBJECTID
	,DU.ID_DUCTO as DU__ID_DUCTO
	,DU.ID_TIPO_DUCTO as DU__ID_TIPO_DUCTO
	,DU.ID_MATERIAL_DUCTO as DU__ID_MATERIAL_DUCTO
	,DU.LONGITUD as DU__LONGITUD
	,DU.OBSERVACION as DU__OBSERVACION
	,DU.ID_TIPO_PROPIEDAD as DU__ID_TIPO_PROPIEDAD
	,DU.ID_PROPIETARIO as DU__ID_PROPIETARIO
	,DU.ID_SITUACION as DU__ID_SITUACION
	,DU.ID_PROYECTO as DU__ID_PROYECTO
	,DU.FECHA_ALTA as DU__FECHA_ALTA
	,DU.FECHA_ACT as DU__FECHA_ACT
	,DU.Shape
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.DUCTO DU, Red.PROYECTO PR
WHERE DU.ID_PROYECTO = PR.ID_PROYECTO;
