SELECT CE.OBJECTID
	,CE.ID_AREA_EDIFICIO as CE__ID_AREA_EDIFICIO
	,CE.ID_SITE_HOLDER as CE__ID_SITE_HOLDER
	,CE.FECHA_ACT as CE__FECHA_ACT
	,CE.FECHA_ALTA as CE__FECHA_ALTA
	,CE.Shape
	,SH.ID_SITE_HOLDER as SH__ID_SITE_HOLDER
	,SH.ID_TIPO_SITE as SH__ID_TIPO_SITE
	,SH.ID_CLASIFICACION_SITE as SH__ID_CLASIFICACION_SITE
	,SH.ID_NUMERO_PREDIAL as SH__ID_NUMERO_PREDIAL
	,SH.CODIGO as SH__CODIGO
	,SH.NODO as SH__NODO
	,SH.ID_TIPO_PROPIEDAD as SH__ID_TIPO_PROPIEDAD
	,SH.ID_PROPIETARIO as SH__ID_PROPIETARIO
	,SH.ID_LOCALIZACION as SH__ID_LOCALIZACION
	,SH.ID_PA as SH__ID_PA
	,SH.ID_PROYECTO as SH__ID_PROYECTO
	,SH.OBSERVACION as SH__OBSERVACION
	,SH.CANTIDAD_PISOS as SH__CANTIDAD_PISOS
	,SH.CANTIDAD_DEPARTAMENTOS as SH__CANTIDAD_DEPARTAMENTOS
	,SH.CANTIDAD_BLOQUES as SH__CANTIDAD_BLOQUES
	,SH.CANTIDAD_DPTOS_X_PISO as SH__CANTIDAD_DPTOS_X_PISO
	,SH.AREA_M2 as SH__AREA_M2
	,SH.FECHA_ALTA as SH__FECHA_ALTA
	,SH.FECHA_ACT as SH__FECHA_ACT
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Cobertura.EDIFICIO_AREA CE, Infraestructura.SITE_HOLDER SH, Red.PROYECTO PR
WHERE CE.ID_SITE_HOLDER = SH.ID_SITE_HOLDER AND SH.ID_PROYECTO = PR.ID_PROYECTO;
