SELECT EV.OBJECTID
	,EV.ID_EJE_VIA as EV__ID_EJE_VIA
	,EV.ID_VIA as EV__ID_VIA
	,EV.ID_DISTRITO as EV__ID_DISTRITO
	,EV.NORMALIZADO as EV__NORMALIZADO
	,EV.OBSERVACION as EV__OBSERVACION
	,EV.FECHA_ALTA as EV__FECHA_ALTA
	,EV.FECHA_ACT as EV__FECHA_ACT
	,EV.Shape
	,VI.ID_VIA as VI__ID_VIA
	,VI.ID_TIPO_VIA as VI__ID_TIPO_VIA
	,VI.NOMBRE as VI__NOMBRE
	,VI.NORMALIZADO as VI__NORMALIZADO
	,VI.FECHA_ALTA as VI__FECHA_ALTA
	,VI.FECHA_ACT as VI__FECHA_ACT
	,DI.ID_DISTRITO as DI__ID_DISTRITO
	,DI.ID_PROVINCIA as DI__ID_PROVINCIA
	,DI.NOMBRE as DI__NOMBRE
	,DI.CODIGO_POSTAL as DI__CODIGO_POSTAL
FROM Cartografia.EJE_VIA EV, Cartografia.VIA VI, Cartografia.DISTRITO DI
WHERE EV.ID_VIA = VI.ID_VIA AND EV.ID_DISTRITO = DI.ID_DISTRITO;
