SELECT FA.OBJECTID
	,FA.ID_FACHADA as FA__ID_FACHADA
	,FA.ID_LOCALIZACION as FA__ID_LOCALIZACION
	,FA.ID_SITUACION as FA__ID_SITUACION
	,FA.ID_PROYECTO as FA__ID_PROYECTO
	,FA.ID_PA as FA__ID_PA
	,FA.FECHA_ALTA as FA__FECHA_ALTA
	,FA.FECHA_ACT as FA__FECHA_ACT
	,FA.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.FACHADA FA, Infraestructura.PA PA, Red.PROYECTO PR
WHERE FA.ID_PA = PA.ID_PA AND FA.ID_PROYECTO = PR.ID_PROYECTO;
