SELECT MA.OBJECTID
	,MA.ID_MANZANA as MA__ID_MANZANA
	,MA.ID_DISTRITO as MA__ID_DISTRITO
	,MA.NOMBRE as MA__NOMBRE
	,MA.CODIGO as MA__CODIGO
	,MA.CANTIDAD_TOTAL as MA__CANTIDAD_TOTAL
	,MA.OCUPACION_RESIDENCIAL as MA__OCUPACION_RESIDENCIAL
	,MA.OCUPACION_NEGOCIO as MA__OCUPACION_NEGOCIO
	,MA.OCUPACION_DEPARTAMENTO as MA__OCUPACION_DEPARTAMENTO
	,MA.INDICADOR as MA__INDICADOR
	,MA.FECHA_ALTA as MA__FECHA_ALTA
	,MA.FECHA_ACT as MA__FECHA_ACT
	,MA.Shape
	,DI.ID_DISTRITO as DI__ID_DISTRITO
	,DI.ID_PROVINCIA as DI__ID_PROVINCIA
	,DI.NOMBRE as DI__NOMBRE
	,DI.CODIGO_POSTAL as DI__CODIGO_POSTAL
FROM Cartografia.Manzana MA, Cartografia.DISTRITO DI
WHERE MA.ID_DISTRITO = DI.ID_DISTRITO;
