SELECT PE.OBJECTID
	,PE.ID_PEDESTAL as PE__ID_PEDESTAL
	,PE.ID_TIPO_PEDESTAL as PE__ID_TIPO_PEDESTAL
	,PE.RUTA as PE__RUTA
	,PE.ID_TIERRA as PE__ID_TIERRA
	,PE.ID_LOCALIZACION as PE__ID_LOCALIZACION
	,PE.ID_TIPO_PROPIEDAD as PE__ID_TIPO_PROPIEDAD
	,PE.ID_PROPIETARIO as PE__ID_PROPIETARIO
	,PE.ID_SITUACION as PE__ID_SITUACION
	,PE.ID_PROYECTO as PE__ID_PROYECTO
	,PE.ID_PA as PE__ID_PA
	,PE.FECHA_ALTA as PE__FECHA_ALTA
	,PE.FECHA_ACT as PE__FECHA_ACT
	,PE.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.PEDESTAL PE, Infraestructura.PA PA, Red.PROYECTO PR
WHERE PE.ID_PA = PA.ID_PA AND PE.ID_PROYECTO = PR.ID_PROYECTO;
