SELECT PD.OBJECTID
	,PD.ID_PREDIAL as PD__ID_PREDIAL
	,PD.ID_VIA as PD__ID_VIA
	,PD.ID_USO_PREDIAL as PD__ID_USO_PREDIAL
	,PD.ID_REF_ATENCION as PD__ID_REF_ATENCION
	,PD.NUMERO as PD__NUMERO
	,PD.NORMALIZADO as PD__NORMALIZADO
	,PD.NUM_PISOS as PD__NUM_PISOS
	,PD.NUM_UIPS as PD__NUM_UIPS
	,PD.INFORMACION_ADICIONAL as PD__INFORMACION_ADICIONAL
	,PD.UNIDADES_MULTIPLES as PD__UNIDADES_MULTIPLES
	,PD.NOMBRE as PD__NOMBRE
	,PD.OBSERVACION as PD__OBSERVACION
	,PD.FECHA_ALTA as PD__FECHA_ALTA
	,PD.FECHA_ACT as PD__FECHA_ACT
	,PD.Shape
	,PD.ID_DISTRITO as PD__ID_DISTRITO
	,VI.ID_VIA as VI__ID_VIA
	,VI.ID_TIPO_VIA as VI__ID_TIPO_VIA
	,VI.NOMBRE as VI__NOMBRE
	,VI.NORMALIZADO as VI__NORMALIZADO
	,VI.FECHA_ALTA as VI__FECHA_ALTA
	,VI.FECHA_ACT as VI__FECHA_ACT
	,DI.ID_DISTRITO as DI__ID_DISTRITO
	,DI.ID_PROVINCIA as DI__ID_PROVINCIA
	,DI.NOMBRE as DI__NOMBRE
	,DI.CODIGO_POSTAL as DI__CODIGO_POSTAL
FROM Cartografia.PREDIAL PD, Cartografia.VIA VI, Cartografia.DISTRITO DI
WHERE PD.ID_VIA = VI.ID_VIA AND PD.ID_DISTRITO = DI.ID_DISTRITO;
