SELECT SH.OBJECTID
	,SH.ID_SITE_HOLDER as SH__ID_SITE_HOLDER
	,SH.ID_TIPO_SITE as SH__ID_TIPO_SITE
	,SH.ID_CLASIFICACION_SITE as SH__ID_CLASIFICACION_SITE
	,SH.ID_NUMERO_PREDIAL as SH__ID_NUMERO_PREDIAL
	,SH.CODIGO as SH__CODIGO
	,SH.NODO as SH__NODO
	,SH.AREA_M2 as SH__AREA_M2
	,SH.OBSERVACION as SH__OBSERVACION
	,SH.ID_LOCALIZACION as SH__ID_LOCALIZACION
	,SH.ID_TIPO_PROPIEDAD as SH__ID_TIPO_PROPIEDAD
	,SH.ID_PROPIETARIO as SH__ID_PROPIETARIO
	,SH.ID_PA as SH__ID_PA
	,SH.ID_PROYECTO as SH__ID_PROYECTO
	,SH.CANTIDAD_PISOS as SH__CANTIDAD_PISOS
	,SH.CANTIDAD_DEPARTAMENTOS as SH__CANTIDAD_DEPARTAMENTOS
	,SH.CANTIDAD_BLOQUES as SH__CANTIDAD_BLOQUES
	,SH.CANTIDAD_DPTOS_X_PISO as SH__CANTIDAD_DPTOS_X_PISO
	,SH.FECHA_ALTA as SH__FECHA_ALTA
	,SH.FECHA_ACT as SH__FECHA_ACT
	,SH.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.SITE_HOLDER SH, Infraestructura.PA PA, red.PROYECTO PR
WHERE SH.ID_PA = PA.ID_PA AND SH.ID_PROYECTO = PR.ID_PROYECTO;
