SELECT SS.OBJECTID
	,SS.ID_SOPORTE_SUSPENSION as SS__ID_SOPORTE_SUSPENSION
	,SS.CODIGO as SS__CODIGO
	,SS.ID_TIPO_SOPORTE_SUSPENSION as SS__ID_TIPO_SOPORTE_SUSPENSION
	,SS.ID_MATERIAL_SOPORTE_SUSPENSION as SS__ID_MATERIAL_SOPORTE_SUSPENSION
	,SS.OBSERVACION as SS__OBSERVACION
	,SS.ID_LOCALIZACION as SS__ID_LOCALIZACION
	,SS.ID_TIPO_PROPIEDAD as SS__ID_TIPO_PROPIEDAD
	,SS.ID_PROPIETARIO as SS__ID_PROPIETARIO
	,SS.ID_SITUACION as SS__ID_SITUACION
	,SS.ID_PROYECTO as SS__ID_PROYECTO
	,SS.FECHA_ALTA as SS__FECHA_ALTA
	,SS.FECHA_ACT as SS__FECHA_ACT
	,SS.Shape
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.SOPORTE_SUSPENSION SS, Red.PROYECTO PR
WHERE SS.ID_PROYECTO = PR.ID_PROYECTO;
