SELECT TM.OBJECTID
	,TM.ID_SOPORTE_T_MENSAJERO as TM__ID_SOPORTE_T_MENSAJERO
	,TM.ID_TIPO_T_MENSAJERO as TM__ID_TIPO_T_MENSAJERO
	,TM.OBSERVACION as TM__OBSERVACION
	,TM.ID_LOCALIZACION as TM__ID_LOCALIZACION
	,TM.ID_TIPO_PROPIEDAD as TM__ID_TIPO_PROPIEDAD
	,TM.ID_PROPIETARIO as TM__ID_PROPIETARIO
	,TM.ID_PROYECTO as TM__ID_PROYECTO
	,TM.ID_SITUACION as TM__ID_SITUACION
	,TM.ID_PA as TM__ID_PA
	,TM.FECHA_ALTA as TM__FECHA_ALTA
	,TM.FECHA_ACT as TM__FECHA_ACT
	,TM.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.SOPORTE_T_MENSAJERO TM, Infraestructura.PA PA, Red.PROYECTO PR
WHERE TM.ID_PA = PA.ID_PA AND TM.ID_PROYECTO = PR.ID_PROYECTO;
