SELECT SA.OBJECTID
	,SA.ID_SOPORTE_ANCLAJE as SA__ID_SOPORTE_ANCLAJE
	,SA.CODIGO as SA__CODIGO
	,SA.ID_TIPO_SOPORTE_ANCLAJE as SA__ID_TIPO_SOPORTE_ANCLAJE
	,SA.ID_MATERIAL_SOPORTE_ANCLAJE as SA__ID_MATERIAL_SOPORTE_ANCLAJE
	,SA.OBSERVACION as SA__OBSERVACION
	,SA.ID_LOCALIZACION as SA__ID_LOCALIZACION
	,SA.ID_TIPO_PROPIEDAD as SA__ID_TIPO_PROPIEDAD
	,SA.ID_PROPIETARIO as SA__ID_PROPIETARIO
	,SA.ID_SITUACION as SA__ID_SITUACION
	,SA.ID_PROYECTO as SA__ID_PROYECTO
	,SA.FECHA_ALTA as SA__FECHA_ALTA
	,SA.FECHA_ACT as SA__FECHA_ACT
	,SA.Shape
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.SOPORTE_ANCLAJE SA, Red.PROYECTO PR
WHERE SA.ID_PROYECTO = PR.ID_PROYECTO;
