SELECT CM.OBJECTID
	,CM.ID_SOPORTE_CRUZ_MENSAJERO as CM__ID_SOPORTE_CRUZ_MENSAJERO
	,CM.ID_TIPO_SOPORTE_CRUZ_MENSAJERO as CM__ID_TIPO_SOPORTE_CRUZ_MENSAJERO
	,CM.OBSERVACION as CM__OBSERVACION
	,CM.ID_LOCALIZACION as CM__ID_LOCALIZACION
	,CM.ID_TIPO_PROPIEDAD as CM__ID_TIPO_PROPIEDAD
	,CM.ID_PROPIETARIO as CM__ID_PROPIETARIO
	,CM.ID_SITUACION as CM__ID_SITUACION
	,CM.ID_PROYECTO as CM__ID_PROYECTO
	,CM.FECHA_ALTA as CM__FECHA_ALTA
	,CM.FECHA_ACT as CM__FECHA_ACT
	,CM.Shape
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.SOPORTE_CRUZ_MENSAJERO CM, Red.PROYECTO PR
WHERE CM.ID_PROYECTO = PR.ID_PROYECTO;
