SELECT SO.OBJECTID
	,SO.ID_SOLERA as SO__ID_SOLERA
	,SO.FECHA_ALTA as SO__FECHA_ALTA
	,SO.FECHA_ACT as SO__FECHA_ACT
	,SO.ID_DISTRITO as SO__ID_DISTRITO
	,SO.Shape
	,DI.ID_DISTRITO as DI__ID_DISTRITO
	,DI.ID_PROVINCIA as DI__ID_PROVINCIA
	,DI.NOMBRE as DI__NOMBRE
	,DI.CODIGO_POSTAL as DI__CODIGO_POSTAL
FROM Cartografia.SOLERA SO, Cartografia.DISTRITO DI
WHERE SO.ID_DISTRITO = DI.ID_DISTRITO;
