SELECT AT.OBJECTID
	,AT.ID_TORRE_ALTA_TENSION as AT__ID_TORRE_ALTA_TENSION
	,AT.ALTURA as AT__ALTURA
	,AT.OBSERVACION as AT__OBSERVACION
	,AT.ID_LOCALIZACION as AT__ID_LOCALIZACION
	,AT.ID_TIPO_PROPIEDAD as AT__ID_TIPO_PROPIEDAD
	,AT.ID_PROPIETARIO as AT__ID_PROPIETARIO
	,AT.ID_SITUACION as AT__ID_SITUACION
	,AT.ID_PROYECTO as AT__ID_PROYECTO
	,AT.ID_PA as AT__ID_PA
	,AT.FECHA_ALTA as AT__FECHA_ALTA
	,AT.FECHA_ACT as AT__FECHA_ACT
	,AT.Shape
    ,PA.OBJECTID as PA__OBJECTID
    ,PA.ID_PA as PA__ID_PA
    ,PA.ID_TIPO_PA as PA__ID_TIPO_PA
    ,PA.FECHA_ALTA as PA__FECHA_ALTA
    ,PA.FECHA_ACT as PA__FECHA_ACT
    ,PA.CODIGO as PA__CODIGO
    ,PR.ID_PROYECTO as PR__ID_PROYECTO
    ,PR.ID_ESTADO_PROYECTO as PR__ID_ESTADO_PROYECTO
    ,PR.ID_TIPO_PROYECTO as PR__ID_TIPO_PROYECTO
    ,PR.ID_CARACTERISTICA as PR__ID_CARACTERISTICA
    ,PR.CODIGO as PR__CODIGO
FROM Infraestructura.TORRE_ALTA_TENSION AT, Infraestructura.PA PA, Red.PROYECTO PR
WHERE AT.ID_PA = PA.ID_PA AND AT.ID_PROYECTO = PR.ID_PROYECTO;
